In [48]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% ! important;}
div.cell.code_cell.rendered{width:100%}
div.input_prompt{padding:0px}
div.CodeMirror {font-family:Consolas ; font-size:12pt;}
div.text_cell_render.rendered_html {font-size:12pt;}
div.output {font-size:12pt; font-weight:bold}
div.input {font-family:Consolas ; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper {padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red">ch.10 N차원 배열(numpy배열)다루기_4절~6절</font></b>
# 4절 복사와 뷰
## 4.1 할당

In [3]:
import numpy as np
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b=a

In [6]:
a.shape, a.ndim, id(a),type(a)

((12,), 1, 2148721079856, numpy.ndarray)

In [7]:
b.shape, b.ndim, id(b),type(b)

((12,), 1, 2148721079856, numpy.ndarray)

In [8]:
a is b

True

In [9]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [11]:
np.all(a==b)

True

In [12]:
b.shape= (3,4) # 할당받은 b의 shape 수정

In [13]:
a.shape, a.ndim, id(a),type(a)

((3, 4), 2, 2148721079856, numpy.ndarray)

In [14]:
b.shape, b.ndim, id(b),type(b)

((3, 4), 2, 2148721079856, numpy.ndarray)

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 4.2 앝은 복사 : 뷰(View)

In [19]:
a =  np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
c=a.view()
print(id(a),id(c))

2148780131792 2148780132464


In [22]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
c.shape=(2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
c[1,::2]=[9,9,9] # 1행의 짝수번째 열 변경(9)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 9,  9,  9, 11]])

## 4.3 깊은 복사

In [42]:
a = np.array([[5,4,13,0], [99,6,16,1], [20,5,14,0]])
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [46]:
# X = a[:,:-1] # 슬라이싱이 될 때, 뷰가 반환됨(얕은 복사)
X=a[:,:-1].copy() # 깊은 복사
# X=np.array(a[:,:-1], copy=True)
X

array([[ 5,  4, 13],
       [99,  6, 16],
       [20,  5, 14]])

In [44]:
X[:,0] = -9 
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [47]:
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절 고급인덱싱